// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_i9dhNovPF3uh8LoukvMTFbBN_uPuwfQ',
    appId: '1:413342340050:web:9130b7c25fda0064ddee0b',
    messagingSenderId: '413342340050',
    projectId: 'myproject1-938b5',
    authDomain: 'myproject1-938b5.firebaseapp.com',
    storageBucket: 'myproject1-938b5.appspot.com',
    measurementId: 'G-6CX36ENRK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq3_wCGWdcbn1Qse68Fv_LAnSaS73R76I',
    appId: '1:413342340050:android:5d5d260fa5529d11ddee0b',
    messagingSenderId: '413342340050',
    projectId: 'myproject1-938b5',
    storageBucket: 'myproject1-938b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6oKFrPYfpyZ29ujenovtD8Hr4O2OnzuQ',
    appId: '1:413342340050:ios:9c8dcdd81fb04c0eddee0b',
    messagingSenderId: '413342340050',
    projectId: 'myproject1-938b5',
    storageBucket: 'myproject1-938b5.appspot.com',
    iosBundleId: 'com.example.culturalspacelibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6oKFrPYfpyZ29ujenovtD8Hr4O2OnzuQ',
    appId: '1:413342340050:ios:9c8dcdd81fb04c0eddee0b',
    messagingSenderId: '413342340050',
    projectId: 'myproject1-938b5',
    storageBucket: 'myproject1-938b5.appspot.com',
    iosBundleId: 'com.example.culturalspacelibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_i9dhNovPF3uh8LoukvMTFbBN_uPuwfQ',
    appId: '1:413342340050:web:2008a21ded198906ddee0b',
    messagingSenderId: '413342340050',
    projectId: 'myproject1-938b5',
    authDomain: 'myproject1-938b5.firebaseapp.com',
    storageBucket: 'myproject1-938b5.appspot.com',
    measurementId: 'G-ZX96FG2LZE',
  );
}
